Adds interface for pre-releasing repo versions on Github
tableflip/adventure pull request #10
Opened 2017-06-05 13:38 UTC by richsilv

2017-06-05 14:58 UTC, olizilla commented
👓

2017-06-05 15:41 UTC, olizilla requested changes
Works good, but running it with an existing tag causes an unhandled promise rejection warning which we don't want.

```
(node:94719) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: e is not defined
(node:94719) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

2017-06-05 15:44 UTC, richsilv commented
That's because you're trying to log `e` rather than `err` in the `catch` block!

2017-06-08 11:31 UTC, alanshaw approved these changes
This looks great - just a few suggestions

2017-06-08 11:31 UTC, alanshaw commented on example/github-interface-cli.js
> +Make sure you've got a github.rc in the project root with your username and an api key.
`github.rc` => `.githubrc`

2017-06-08 11:31 UTC, alanshaw commented on lib/github-interface.js
> +}
Suggestion - ensure all provided repos exist and the tag/release doesn't already exist. Otherwise we're in an inconsistent state on failure.

2017-06-08 11:31 UTC, alanshaw commented on lib/github-interface.js
> +async function prerelease ({ repos, version, message }) {
Suggestions
* Allow repos to be a string (auto arrayify)
* Validate version is a [prerelease semver](http://semver.org/#spec-item-9) (or at least a semver)

2017-06-09 10:21 UTC, bmordan commented
Works nice - merging to master work continues on `github-release-stats` branch

2017-06-09 10:21 UTC, merged