GitHub release stats
tableflip/adventure pull request #12
Opened 2017-06-05 16:28 UTC by richsilv

Adds function to calculate aggregate stats (number of commits, lines added, lines removed) for the supplied repos and a given version number.

Stats are calculated on the basis of comparison to the previous version, or else the whole commit history if this is the first tag.

Also adds a CLI example, which can be run with:

```sh
> node example/github-release-stats-cli.js --repo olizilla/tags --version v2.0.0
```

2017-06-08 11:33 UTC, alanshaw commented
👓

2017-06-08 11:57 UTC, alanshaw requested changes
I got the following error:
`Error: Cannot find module 'mime-types'`

Removing `package-lock.json` and re-installing solved it, but left me with a `package-lock.json` with many changes from the original.

2017-06-08 11:57 UTC, alanshaw commented on example/github-release-stats-cli.js
> +Make sure you've got a github.rc in the project root with your username and an api key.
.githubrc

2017-06-08 11:57 UTC, alanshaw commented on lib/github-interface.js
> +  }
Just comparing this with the [pulse page](https://github.com/tableflip/study-bundles-app/pulse), can we return the number of files changed, PRs merged and issues closed?

2017-06-09 11:55 UTC, bmordan commented on lib/github-interface.js
> +  }
Lets do this later it is quite tricky

2017-06-09 11:55 UTC, merged